[package]
name = "ocd-cli"
version = "0.0.1"
authors = ["Iñaki Garay <igarai@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/igaray/ocd-cli"
repository = "https://github.com/igaray/ocd-cli"
documentation = "https://docs.rs/ocd-cli"
readme = "README.md"
keywords = ["cli","file","rename"]
categories = ["command-line-utilities","filesystem"]
description = """
A CLI file management swiss army knife.
"""

[[bin]]
name = "ocd"
path = "src/main.rs"

[dependencies]
clap = {version = "2", features = ["yaml"]}
dialoguer = "0.3.0"
kamadak-exif = "0.3"
glob = "0.2"
lazy_static = "1.3"
regex = "1"
walkdir = "2"
unicode-segmentation = "1"
remain = "0.2"
chrono = "0.4"
voca_rs = "1"
# case = "1.0.0"
# heck = "0.3.1"
# Inflector = "0.11.4"
# string_morph = "0.1.0"
# id3 = "0.3.0"
