[package]
name = "ocd"
version = "0.1.0"
authors = ["Iñaki Garay <igarai@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
dialoguer = "0.3.0"
glob = "0.2"
lazy_static = "1.3.0"
regex = "1.0.0"
walkdir = "2.1.4"
# id3 = "0.3.0"
# voca_rs = "1.6.1"
# case = "1.0.0"
# heck = "0.3.1"
# Inflector = "0.11.4"
# string_morph = "0.1.0"
