[package]
name = "ocd"
version = "0.1.0"
authors = ["Iñaki Garay <igarai@gmail.com>"]

[dependencies]
assert_cli = "0.6.1"
clap = "2.31.2"
clierr = "0.7.0"
glob = "0.2"
heck = "0.3.1"
regex = "1.0.0"
walkdir = "2.1.4"
