[package]
name = "ocd"
version = "0.1.0"
authors = ["Iñaki Garay <igarai@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
glob = "0.2"
regex = "1.0.0"
walkdir = "2.1.4"
dialoguer = "0.3.0"
